export default {
	basic: [
		{
			name: 'Identifiant',
			helpTextTitle: 'Identifiant unique du contact',
			helpText:
				"Il servira pour le rechercher à travers l'annuaire.",
			getFunctionName: 'GetElementFromRoot',
			setFunctionName: 'SetElementToRoot',
			varName: 'username',
			modifiable: true,
		},
		{
			name: 'Nom commun',
			helpTextTitle: ' Nom commun du contact ',
			helpText:
				" Il servira pour le rechercher à travers l'annuaire. Caractères autorisés : alphabétiques chiffres apostrophes espaces tirets",
			getFunctionName: 'GetElementFromAttributes',
			setFunctionName: 'SetElementToAttributes',
			varName: 'common_name',
			modifiable: true,
		},
		{
			name: 'Nom',
			helpTextTitle: ' Nom du contact ',
			helpText:
				'Caractères autorisés : alphabétiques chiffres apostrophes espaces tirets',
			getFunctionName: 'GetElementFromRoot',
			setFunctionName: 'SetElementToRoot',
			varName: 'lastname',
			modifiable: true,
		},
		{
			name: 'Prénom',
			helpTextTitle: ' Prénom du contact ',
			helpText:
				'Caractères autorisés : alphabétiques chiffres apostrophes espaces tirets',
			getFunctionName: 'GetElementFromRoot',
			setFunctionName: 'SetElementToRoot',
			varName: 'firstName',
			modifiable: true,
		},
		{
			name: 'Adresse e-mail',
			helpTextTitle: ' Adresse de messagerie du contact ',
			helpText:
				"Elle servira pour la rechercher à travers l'annuaire. ",
			getFunctionName: 'GetElementFromRoot',
			setFunctionName: 'SetElementToRoot',
			varName: 'mail',
			modifiable: true,
		},
		{
			name: 'Numéro de téléphone',
			helpTextTitle: '  Numéro de téléphone du contact ',
			helpText:
				'Entre 1 et 25 caractères numériques, points, tirets, parenthèses, signe plus, et espaces uniquement. ',
			getFunctionName: 'GetElementFromAttributes',
			setFunctionName: 'SetElementToAttributes',
			varName: 'phone_number',
			modifiable: true,
		},
		{
			name: 'Description',
			helpTextTitle: ' Description du contact ',
			getFunctionName: 'GetElementFromAttributes',
			setFunctionName: 'SetElementToAttributes',
			varName: 'description',
			modifiable: true,
		},
		{
			name: 'Organisation',
			helpTextTitle: "Organisation d'appartenance de l'agent",
			getFunctionName: 'GetElementFromAttributes',
			setFunctionName: 'SetElementToAttributes',
			varName: 'organization',
			modifiable: true,
		},
		{
			name: "Timbre de l'agent",
			getFunctionName: 'GetElementFromAttributes',
			setFunctionName: 'SetElementToAttributes',
			varName: 'insee_timbre',
			modifiable: true,
		},
		{
			name: "Organisme de l'agent",
			getFunctionName: 'GetElementFromAttributes',
			setFunctionName: 'SetElementToAttributes',
			varName: 'insee_organisme',
			modifiable: true,
		},
	],
	address: [
		{
			name: 'Identification du destinataire',
			helpTextTitle: ' Identification du destinataire ',
			helpText: 'Exemple : M. Valéry FRONTERE',
			getFunctionName: 'GetElementFromAddress',
			setFunctionName: 'SetElementToAddress',
			varName: 'ligne1',
			modifiable: false,
		},
		{
			name: 'N° appartement, boite aux lettres, étage, couloire',
			helpTextTitle:
				' N° appartement, boite aux lettres, étage, couloir ',
			helpText: 'Exemple : Appartement 12 Escalier C',
			getFunctionName: 'GetElementFromAddress',
			setFunctionName: 'SetElementToAddress',
			varName: 'ligne2',
			modifiable: true,
		},
		{
			name: 'Entrée, tour, bâtiment, immeuble, résidence',
			helpTextTitle:
				' Entrée, tour, bâtiment, immeuble, résidence ',
			helpText: 'Exemple : Résidence Les Tilleuls',
			getFunctionName: 'GetElementFromAddress',
			setFunctionName: 'SetElementToAddress',
			varName: 'ligne3',
			modifiable: true,
		},
		{
			name: 'Numéro et libellé de la voie',
			helpTextTitle: ' Numéro et libellé de la voie ',
			helpText: 'Exemple : 1 impasse de l Eglise',
			getFunctionName: 'GetElementFromAddress',
			setFunctionName: 'SetElementToAddress',
			varName: 'ligne4',
			modifiable: true,
		},
		{
			name: 'Lieu dit ou boîte postale',
			helpTextTitle: ' Lieu dit ou boîte postale ',
			helpText: 'Exemple : AMAREINS',
			getFunctionName: 'GetElementFromAddress',
			setFunctionName: 'SetElementToAddress',
			varName: 'ligne5',
			modifiable: true,
		},
		{
			name: 'Code postal et localité de destination',
			helpTextTitle: ' Code postal et localité de destination ',
			helpText: 'Exemple : 01090 FRANCHELEINS',
			getFunctionName: 'GetElementFromAddress',
			setFunctionName: 'SetElementToAddress',
			varName: 'ligne6',
			modifiable: true,
		},
		{
			name: 'Pays',
			helpTextTitle: 'Pays',
			helpText: 'Exemple : FRANCE',
			getFunctionName: 'GetElementFromAddress',
			setFunctionName: 'SetElementToAddress',
			varName: 'ligne7',
			modifiable: true,
		},
	],
	advanced: [
		{
			name: 'Organisation de rattachement',
			helpTextTitle: ' Organisation de rattachement',
			getFunctionName: 'GetElementFromAttributes',
			setFunctionName: 'SetElementToAttributes',
			varName: 'org_rattachement',
			modifiable: true,
		},
		{
			name: 'Identifiant métier',
			helpTextTitle: ' Identifiant métier du contact ',
			getFunctionName: 'GetElementFromAttributes',
			setFunctionName: 'SetElementToAttributes',
			varName: 'id_métier',
			modifiable: true,
		},
		{
			name: ' Répertoire de distribution ',
			helpTextTitle: '  Répertoire de distribution ',
			getFunctionName: 'GetElementFromAttributes',
			setFunctionName: 'SetElementToAttributes',
			varName: 'rep_distribution',
			modifiable: true,
		},
		{
			name: ' Téléphone portable ',
			helpTextTitle: ' Numéro de téléphone portable du contact ',
			helpText:
				'Entre 1 et 25 caractères numériques, points, tirets, parenthèses, signe plus, et espaces uniquement. ',
			getFunctionName: 'GetElementFromAttributes',
			setFunctionName: 'SetElementToAttributes',
			varName: 'tel_portable',
			modifiable: true,
		},
		{
			name: 'Fax',
			helpTextTitle: ' Numéro de fax du contact ',
			helpText:
				'Entre 1 et 25 caractères numériques, points, tirets, parenthèses, signe plus, et espaces uniquement. ',
			getFunctionName: 'GetElementFromAttributes',
			setFunctionName: 'SetElementToAttributes',
			varName: 'id_métier',
			modifiable: true,
		},
	],
};
