name: Sugoi UI CI

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 22.18.0
        uses: actions/setup-node@v1
        with:
          node-version: 22.18.0
      - run: yarn --frozen-lockfile
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.18.0
        uses: actions/setup-node@v1
        with:
          node-version: 22.18.0
      - run: yarn
      - run: yarn lint
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.18.0
        uses: actions/setup-node@v1
        with:
          node-version: 22.18.0
      - run: yarn install
      - run: yarn start & yarn wait-on http://localhost:3000
      - run: yarn cypress run
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.18.0
        uses: actions/setup-node@v1
        with:
          node-version: 22.18.0
      - run: yarn
      - run: yarn build
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
