name: Release sugoi-ui

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the release"
        required: true

jobs:
  pre-release:
    name: pre-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install -g pnpm
      - name: Prepare
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
        run: |
          git config --global user.name "Insee - Team sugoi"
          git config --global user.email "sugoi@insee.fr"
          git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}.git
          cd sugoi-ui/
          git checkout -b release-$VERSION
          pnpm version $VERSION --no-git-tag-version
          git add package.json
          git commit -s -m "[REL] :rocket: Release version $VERSION"
          git push origin release-$VERSION -f
          gh pr create --title "[REL] :rocket: prepare new version $VERSION" --body "[REL] :rocket: prepare new version $VERSION"

  release:
    name: release
    runs-on: ubuntu-latest
    needs: pre-release
    permissions:
      contents: write
    steps:
      - name: Clone Deployments repo
        uses: actions/checkout@v6
        with:
          repository: ${{github.repository}}
          ref: release-${{ github.event.inputs.version }}
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install -g pnpm

      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile

      - name: Build with pnpm
        run: pnpm build
        

      - uses: vimtor/action-zip@v1
        name: Zip build
        with:
          files: dist/
          dest: sugoi-ui-${{ github.event.inputs.version }}-distribution.zip

      - name: Create a release and upload asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
        run: |
          gh release create "$VERSION" \
            "sugoi-ui-${VERSION}-distribution.zip" \
            --repo "${{ github.repository }}" \
            --title "$VERSION" \
            --generate-notes

  after-release:
    name: after-release
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install -g pnpm
      - name: Prepare next version
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          git config --global user.name "Insee - Team sugoi"
          git config --global user.email "sugoi@insee.fr"
          git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}.git
          cd sugoi-ui/
          git checkout release-$VERSION
          pnpm version minor --no-git-tag-version --no-git-checks
          pnpm version prerelease --no-git-tag-version --no-git-checks
          git add package.json
          git commit -s -m "[ENH] :sparkles: prepare next version"
          git push origin release-$VERSION
